# @host = 192.168.8.211:8087
@host = localhost:8087

###
GET http://{{host}}/api/users HTTP/1.1

###
POST http://{{host}}/api/user HTTP/1.1
Content-Type: application/json

{
    "UserId": "022771d3e0167f49da17db71354dbffffcc0e8c37548b93df77c38043e217050",
    "Labels": null,
    "Subscribe": null,
    "Comment": ""
}

###
GET http://{{host}}/api/items HTTP/1.1

###
POST http://{{host}}/api/item HTTP/1.1
Content-Type: application/json

{
    "ItemId": "idontknow",
    "IsHidden": false,
    "Categories": null,
    "Timestamp": "2023-06-11T15:51:12Z",
    "Heating": 0,
    "Comment": "idontknow"
}

###
PATCH http://{{host}}/api/item/007a01cacba4455ce87eb46aa79d0881dfe120fb16f9dba602a1ff0b347f1491 HTTP/1.1
Content-Type: application/json

{
    "IsHidden": false,
    "Timestamp": "2023-06-11T15:52:12Z",
    "Heating": 1000
}

###
GET http://{{host}}/api/item//65de32c8c94cb526f28ea654b2397e07da3lac721c9524627f73845ddc6fafaa HTTP/1.1

###
GET http://{{host}}/api/latest HTTP/1.1

###
GET http://{{host}}/api/popular HTTP/1.1

###
GET http://{{host}}/api/recommend/022771d3e0167f49da17db71354dbffffcc0e8c37548b93df77c38043e217050 HTTP/1.1

###
GET http://{{host}}/api/feedback HTTP/1.1

###
POST http://{{host}}/api/feedback HTTP/1.1
Content-Type: application/json

[
    {
        "Comment": "",
        "FeedbackType": "read",
        "ItemId": "idontknow",
        "Timestamp": "2023-06-16T15:51:12Z",
        "UserId": "022771d3e0167f49da17db71354dbffffcc0e8c37548b93df77c38043e217050"
    }
]
