# @host = 192.168.8.211:8087
@host = localhost:8087

###
GET http://{{host}}/api/users HTTP/1.1

###
POST http://{{host}}/api/user HTTP/1.1
Content-Type: application/json

{
    "UserId": "022771d3e0167f49da17db71354dbffffcc0e8c37548b93df77c38043e217050",
    "Labels": ["chat"],
    "Subscribe": null,
    "Comment": ""
}

###
GET http://{{host}}/api/items HTTP/1.1

###
POST http://{{host}}/api/item HTTP/1.1
Content-Type: application/json

{
    "ItemId": "idontknow",
    "IsHidden": false,
    "Categories": ["default"],
    "Timestamp": "2023-06-11T15:51:12Z",
    "Labels": ["chat"],
    "Heating": 0,
    "Comment": "idontknow"
}

###
PATCH http://{{host}}/api/item/709749b6cc30949f8c3b98fed40cdd7d697232a60ece705399dadb050b342285 HTTP/1.1
Content-Type: application/json

{
    "IsHidden": false,
    "Timestamp": "2023-06-11T15:52:12Z",
    "Heating": 1000
}

###
GET http://{{host}}/api/user/022771d3e0167f49da17db71354dbffffcc0e8c37548b93df77c38043e217050 HTTP/1.1

###
GET http://{{host}}/api/item/709749b6cc30949f8c3b98fed40cdd7d697232a60ece705399dadb050b342285 HTTP/1.1

###
GET http://{{host}}/api/latest HTTP/1.1

###
GET http://{{host}}/api/popular HTTP/1.1

###
GET http://{{host}}/api/recommend/045210293d2c45c7cca03349509d1aa50d66c9495ca81eb0a9e769eb08ca6819 HTTP/1.1

###
GET http://{{host}}/api/feedback HTTP/1.1

###
POST http://{{host}}/api/feedback HTTP/1.1
Content-Type: application/json

[
    {
        "Comment": "",
        "FeedbackType": "read",
        "ItemId": "09e05d9def26adc0de9b7f9e5f0162c611b35348afa2ab9c183a1f1a727472b7",
        "Timestamp": "2023-06-17T05:01:12Z",
        "UserId": "045210293d2c45c7cca03349509d1aa50d66c9495ca81eb0a9e769eb08ca6819"
    }
]
