name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push-image:
    strategy:
      matrix:
        image: [gorse-master, gorse-server, gorse-worker, gorse-in-one]
      fail-fast: true
    name: Build and push container image
    runs-on: ubuntu-22.04
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get git commit hash
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: cmd/${{ matrix.image }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/denostr-lab/${{ matrix.image }}:latest
            ${{ env.REGISTRY }}/denostr-lab/${{ matrix.image }}:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
            ${{ env.REGISTRY }}/denostr-lab/${{ matrix.image }}:${{ steps.get_version.outputs.version-without-v }}
